### ISSUE TITLE
16本电子商务2班范垂森

### ISSUE THREAD

**Issue by Tonmy73** [huashangxueyuan/hackathon_exercise_1#104]
https://github.com/Tonmy73/Tonmy73.github.io
学习心得：这次的第一个实验是学习如何操作github以及下载安装，通过这次的自主学习，我注册了自己的一个github账号，并根据引导设置了自己的SSHkey公钥，另外，我还掌握了一些github的基本命令，比如如何创建仓库，克隆仓库，添加到缓存区和HEAD区，最终发送到仓库等等一些操作命令，我会创建了自己github page，学习了另外一种发送仓库的指令，很高兴可以自学这么多的知识，感谢学校提供的这么一个平台！

**Comment by Candiceljy** [comment]
非常棒，继续加油！
