### ISSUE TITLE
17计科国际班冼丽铧

### ISSUE THREAD

**Issue by liva0** [huashangxueyuan/hackathon_exercise_1#105]
https://github.com/liva0/firsthub

 # Hello world , I am liva !我是冼丽铧,很高兴参加这个比赛,这一个星期事情太多,所以才把第一章在周六学完,看到很多同学已经上交了作业.我很庆幸这个比赛是以马拉松的形式举行,让我可以在即使跑得慢的情况下也有信心去学习,去继续做下去.最后希望我在这个比赛真正的有所收获!

**Comment by Candiceljy** [comment]
非常棒，继续加油！
