### ISSUE TITLE
18本网络与新媒体二班郭林林

### ISSUE THREAD

**Issue by MRGLIN** [huashangxueyuan/hackathon_exercise_1#119]
老师你好 这是我的代码仓库地址 https://github.com/MRGLIN/quickstart 请老师审核
我想说的是 怪不得他们都说做这一行的容易秃头 这是真的

**Comment by Candiceljy** [comment]
嘻嘻~首先恭喜你完成了站点一的考核，接下来可以好好攻克站点二html和css的练习。秃顶和这一行关系不完全相关哦~另外hackathon_exercise_1这个是练习地址，hackathon_round_1 才是任务地址 哦
