### ISSUE TITLE
16本国贸2班  金阳

### ISSUE THREAD

**Issue by jinyang01** [huashangxueyuan/hackathon_exercise_1#129]

**Comment by Candiceljy** [comment]
oh~你的仓库地址呢?

**Comment by jinyang01** [comment]
我不知道你回复的是哪一份，所以附上三个仓库的地址哦。
1.https://github.com/jinyang01/jinyang01.github.io.git
2.git@github.com:jinyang01/firsthub.git
3.https://github.com/jinyang01/quickstart.git
