### ISSUE TITLE
16本会计学6班 谢志霖

### ISSUE THREAD

**Issue by xiezhiling** [huashangxueyuan/hackathon_exercise_1#136]
我的编码地址：
https://github.com/xiezhiling/xiezhiling.github.io
https://github.com/xiezhiling/firsthub

**Comment by Candiceljy** [comment]
能够清楚知道自己将来要做什么，非常棒，希望你能在这次活动中获得更多的知识，学到更多的东西。继续加油，学习上遇到不懂的积极在群上提问，或者找工程师，指导员问问。因为单单这个比赛学到的东西还不算很完整。找好目标就要努力实现。加油！
