### ISSUE TITLE
16计科1班谢欣蓓

### ISSUE THREAD

**Issue by Bella-X** [huashangxueyuan/hackathon_exercise_1#144]
我的第一个实战训练：https://github.com/Bella-X/firsthub
希望老师指点一下，谢谢

**Comment by Bella-X** [comment]
老师不好意思，训练的作业修正一下：
https://github.com/Bella-X/Bella.github.io

**Comment by Candiceljy** [comment]
非常棒！继续加油！希望能够在终点站看到你。
