### ISSUE TITLE
18本会计一班 郑俊彦

### ISSUE THREAD

**Issue by modernstupidnoob** [huashangxueyuan/hackathon_exercise_1#150]
http：https://github.com/modernstupidnoob/zhengjunyan.github.io.git

**Comment by Candiceljy** [comment]
非常棒！认真去学你会发现不难，很容易，每一次的挑战都是一个激励，学习一个个知识，通过一个个站点，都会让你觉得很有成就感，有动力有信心去把编程学好。继续加油！
