### ISSUE TITLE
16本电商4班-霍泳珊

### ISSUE THREAD

**Issue by Hovisan** [huashangxueyuan/hackathon_exercise_1#164]
我的代码地址：https://github.com/Hovisan/Hovisan.github.io   麻烦老师审核！其中，对于代码的理解上还是有一些地方不太懂，只是按照图片上的步骤进行，有个地方需要选择yes or no，图片上没有说明，还有就是有些细节方面（敲打时没有注意空格）没注意就会导致无法正确运行，我想问一下之后可以把图片和文字结合得更好来帮助我们学习吗？谢谢老师

**Comment by Candiceljy** [comment]
非常棒完成练习，很开心可以看到你的的反馈，我们会认真对待并改进。另外，选择yes or no是有在图文上说明的哦，认真看看github peges。
