### ISSUE TITLE
18 财务管理三班方翠燕

### ISSUE THREAD

**Issue by chaincuiyan** [huashangxueyuan/hackathon_exercise_1#172]
老师好，不好意思这么迟才交到作业，而且一开始还交错了，麻烦老师啦，下面是我的仓库地址
https://github.com/chaincuiyan/chaincuiyan.github.io

**Comment by Candiceljy** [comment]
非常棒！欣赏你的坚持，加油，希望你能看到你每一个任务。

**Comment by Candiceljy** [comment]
非常棒，继续加油！
