### ISSUE TITLE
17审计学班郑少杏

### ISSUE THREAD

**Issue by sx002** [huashangxueyuan/hackathon_exercise_1#179]
git@github.com:sx002/sx002.github.io.git

**Comment by Candiceljy** [comment]
提交的是仓库地址https，你这个是 ssh？

**Comment by Benson-L** [comment]
我提交的是http

**Comment by Benson-L** [comment]
我重新提交一个了




------------------ 原始邮件 ------------------
发件人: "Candiceljy"<notifications@github.com>;
发送时间: 2018年11月7日(星期三) 上午10:32
收件人: "huashangxueyuan/hackathon_exercise_1"<hackathon_exercise_1@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [huashangxueyuan/hackathon_exercise_1] 17审计学班郑少杏 (#179)




提交的是仓库地址https，你这个是 ssh？
