### ISSUE TITLE
17计科2班黄寿辉

### ISSUE THREAD

**Issue by wanttong** [huashangxueyuan/hackathon_exercise_1#22]
https://github.com/wanttong/firsthub.git
这是第二次提交0.0，这个任务很快就做好了，非常期待后面的呢，希望一切顺利

**Comment by Candiceljy** [comment]
看清楚作业内容哦，作业需要创建一个github page 你这个只是命令操作哦，加油已经非常棒了，在完成下一步创建一个github page 就可以了。

**Comment by wanttong** [comment]
github pagess::::    https://github.com/wanttong/-wanttong-.github.io.git

**Comment by wanttong** [comment]
page:   https://wanttong.github.io
