### ISSUE TITLE
17电商1班-黄俊平

### ISSUE THREAD

**Issue by xbackjunping** [huashangxueyuan/hackathon_exercise_1#30]
我的代码仓库地址：https://github.com/xbackjunping/firsthub.git

**Comment by Candiceljy** [comment]
oh~认真看看练习任务哦，花半个小时参照GitHub pages的教程走，就可以完成练习了。

**Comment by xbackjunping** [comment]
重新跟着Github pages的教程完成的地址：https://github.com/xbackjunping/xbackjunping.github.io.git

**Comment by xbackjunping** [comment]
傻傻的删除了仓库又重新做了一遍：https://xbackjunping.github.io/

**Comment by Candiceljy** [comment]
非常棒！继续加油!
