### ISSUE TITLE
16电二-文君杰

### ISSUE THREAD

**Issue by jiejiejie123** [huashangxueyuan/hackathon_exercise_1#34]
这是我的代码地址： https://jiejiejie123.github.io/
                                   https://github.com/jiejiejie123/jiejiejie123.github.io

**Comment by jiejiejie123** [comment]
这是我的代码地址：https://jiejiejie123.github.io/ 
https://github.com/jiejiejie123/jiejiejie123.github.io

**Comment by Candiceljy** [comment]
非常棒！继续加油!
