### ISSUE TITLE
17计科3班-黄燕惟

### ISSUE THREAD

**Issue by Huangyanwei** [huashangxueyuan/hackathon_exercise_1#39]
第一次作业的体验良好，希望在接下来的课程里学习到更多。
这里是第一次作业的代码地址：
https://github.com/Huangyanwei/firsthub/blob/master/README.md

**Comment by Candiceljy** [comment]
非常棒！完成的很快，英语是一个非常重要的学科哦，在以后的生活工作中会经常用到，借此机会好好学习英语，加油！
