### ISSUE TITLE
16本会计6班-施莹美

### ISSUE THREAD

**Issue by simy888** [huashangxueyuan/hackathon_exercise_1#41]
这是我的作业：https://github.com/simy888/first-hub/blob/master/README.md
谢谢老师耐心的解答~

**Comment by Candiceljy** [comment]
非常棒.你已经完成了前面的firsthub了，认真看看练习要求哦，后面还有一个github page的创建，花半个小时根据GitHub pages的教程走，就可以完成这个练习啦!继续加油1
