### ISSUE TITLE
16本信管 杨翠珊

### ISSUE THREAD

**Issue by YonionY** [huashangxueyuan/hackathon_exercise_1#5]
GitHub：https://github.com/YonionY
GitHub作业：https://github.com/YonionY/YonionY.github.io

**Comment by zhuayu** [comment]
非常棒，如果对命令行不是很熟悉，建议多操作几次。重复做几次，自然就理解和记住了，同时要理解每个步骤的意思，为什么要这么做。这次主要目的是体验，砍了一些知识点，如果编程的能带给你乐趣，那就坚持学习下去。希望这次活动之后，能达到你的预期。非常棒，继续加油！

**Comment by Candiceljy** [comment]
1. 作业完成的速度和质量都很不错，说明你的执行能力以及自学能力挺强的。
2. 凡是都有第一次，多去尝试学习新知识会让你变得更优秀。
3. 如果觉得命令很多很难记，不知道它的规律，很苦恼的话，建议你每次完成作业后，多留意群上有没有同学遇到和你一样的问题，或者你对某个环节比较熟悉的话，可以尝试指导一下其他同学，这样你掌握的知识会更加牢固。你会在比赛中获得更多意向不到的知识哦。加油！
