### ISSUE TITLE
18本软件工程3班-梁泽超

### ISSUE THREAD

**Issue by Feijianke** [huashangxueyuan/hackathon_exercise_1#51]
我的代码地址：https://feijianke.github.io/

**Comment by Candiceljy** [comment]
Hello，Feijianke .英语是一个很重要的工具哦，不管你是现在学习编程还是以后的日常生活，都会常常需要用到英语，希望你可以利用这个平台多自己尝试去理解英文的意思，有助于帮助你提高你的英语水平。继续加油！
