### ISSUE TITLE
17计科2班詹鸿钊

### ISSUE THREAD

**Issue by zhanhongzhao** [huashangxueyuan/hackathon_exercise_1#6]
好了 https://github.com/zhanhongzhao/zhanhongzhao.github.io

**Comment by zhanhongzhao** [comment]
代码仓库地址 https://github.com/zhanhongzhao/zhanhongzhao.github.io
个人Github Page https://zhanhongzhao.github.io/

**Comment by zhuayu** [comment]
加油！英文的能力在以后阅读还是工作中都用得上，不然有可能错过半个世界的精彩，加油吧。

**Comment by Candiceljy** [comment]
嘻嘻，你觉得很难的东西你都已经克服了，完成了第一个练习，说明你已经很棒了。万事开头难，接下来只要用心跟着赛程步伐走，你会收获不一样的成果哦，相信整个马拉松跑完你的英文能力也有所提高，加油！

**Comment by zhanhongzhao** [comment]
> 加油！英文的能力在以后阅读还是工作中都用得上，不然有可能错过半个世界的精彩，加油吧。

好的，谢谢。

**Comment by zhanhongzhao** [comment]
> 嘻嘻，你觉得很难的东西你都已经克服了，完成了第一个练习，说明你已经很棒了。万事开头难，接下来只要用心跟着赛程步伐走，你会收获不一样的成果哦，相信整个马拉松跑完你的英文能力也有所提高，加油！

好的，谢谢。
