### ISSUE TITLE
18软件工程2班-甘俊汶

### ISSUE THREAD

**Issue by JOWANONE** [huashangxueyuan/hackathon_exercise_1#62]
我的代码地址：https://github.com/JOWANONE/firsthub/blob/master/README.md，麻烦老师检查，看看代码地址对不对。

**Comment by JOWANONE** [comment]
https://github.com/JOWANONE/firsthub

**Comment by Candiceljy** [comment]
不管是学习编程或者是学习什么，细心是很重要的哦，你已经完成了练习的大部分了，就差github page 认真看看练习要求和GitHub pages的指导，继续加油!

**Comment by JOWANONE** [comment]
我的代码地址：https://github.com/JOWANONE/JOWANONE.github.io

**Comment by Candiceljy** [comment]
非常棒，继续加油！
