### ISSUE TITLE
17计科1班冯南飞

### ISSUE THREAD

**Issue by tiaotiaoaifei** [huashangxueyuan/hackathon_exercise_1#63]
仓库地址：https://github.com/tiaotiaoaifei/tiaotiaoaifei.github.io
代码地址：tiaotiaoaifei.github.io

**Comment by tiaotiaoaifei** [comment]
那个代码地址：https:///tiaotiaoaifei.github.io
这样应该能打开了

**Comment by Candiceljy** [comment]
专心学习，你会发现你可以用更少的时间完成每一个站点练习和任务，更加有成就感，收获的更多，继续加油！
