### ISSUE TITLE
16本会计学6班 陈茗蕊

### ISSUE THREAD

**Issue by gagaandwilliam** [huashangxueyuan/hackathon_exercise_1#70]
老师你好 这是我的实战训练https://github.com/gagaandwilliam/gagaandwilliam.github.io.git

**Comment by gagaandwilliam** [comment]
老师你好 这是我的站点任务https://github.com/gagaandwilliam/quickstart.git

**Comment by Candiceljy** [comment]
哇哇！非常非常帮！学习交流群的初衷就是为了让更多的初学者能够在群上提问题，自主学习然后再把自己的学习的知识传授给其他参赛者。你能在这个群上获得想要的知识并且分享自己的经验，知识。就是这个群存在的价值，希望有更多的参赛者和你一样能够一起参与群学习氛围的维护。加油！你一定可以在这次比赛中获得好的成绩，也能够在这次比赛中获得更多的知识。

另外，站点任务是提交在https://github.com/huashangxueyuan/hackathon_round_1上哦。
