### ISSUE TITLE
18计科-曾浩宇

### ISSUE THREAD

**Issue by HDZM** [huashangxueyuan/hackathon_exercise_1#72]
我的代码地址https://github.com/HDZM/HDZM.github.io    麻烦老师审核
关于github page 中为仓库添加一个README.md 文件的第一个方法是省略了在桌面上创建一个名字为仓库名的文件夹或者克隆那个空仓库吗???

**Comment by zhuayu** [comment]
创建为空仓库就克隆。创建空仓库就直接推送。

**Comment by HDZM** [comment]
没太懂创建空仓库就直接推送???
