### ISSUE TITLE
15本电商3班-欧华贤

### ISSUE THREAD

**Issue by Ouhuaxian** [huashangxueyuan/hackathon_exercise_1#76]
我的远程仓库地址是：    https://github.com/Ouhuaxian/Jessie_xian.git
改了一下   https://github.com/Ouhuaxian/.github.io.git
https://github.com/Ouhuaxian/.github.io

**Comment by Ouhuaxian** [comment]
改了一下   https://github.com/Ouhuaxian/.github.io.git

**Comment by Candiceljy** [comment]
嘻嘻~优秀！能重复认真看要求说明你也很追求完美，适合做程序员哦
