### ISSUE TITLE
17本市场营销3班  王恒

### ISSUE THREAD

**Issue by miedoso** [huashangxueyuan/hackathon_exercise_1#77]
我的代码地址   https://miedoso.github.io/  ，麻烦老师审核了！！
对这个还是感觉很好玩的诶，哈哈哈。想进入下一轮了，就是有的代码是复制的 不知道要不要背下来呀这些。。。emmm

**Comment by Candiceljy** [comment]
非常棒，完成了站点一的练习。代码多敲就可以会熟记于心了，加油！在终点等你！
