### ISSUE TITLE
18计科5班-罗啟源

### ISSUE THREAD

**Issue by Lawkaizen** [huashangxueyuan/hackathon_exercise_1#92]
这是我的作业地址请老师检查     https://github.com/Lawkaizen/work

**Comment by Lawkaizen** [comment]
小程序作业https://github.com/Lawkaizen/Lawkaizen.github.io

**Comment by Lawkaizen** [comment]
老师快检查我。。。漏我了

**Comment by Candiceljy** [comment]
非常棒，完成的很好，希望能够在终极站点看到你的作品，继续加油！
